default:
  image: docker:latest

stages:
  - github_sync

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

github_sync:
  stage: github_sync
  allow_failure: false
  only:
    - master
  script:
    - git remote set-url upstream https://${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN}@github.com/CubicrootXYZ/lightweight-monitoring.git
    - git fetch upstream
    - git checkout upstream/main
    - git merge origin/master --allow-unrelated-histories
    - git push upstream HEAD:main
    - git checkout origin/master
    - git merge upstream/main --allow-unrelated-histories
    - git push origin HEAD:master