default:
  image: docker:latest

stages:
  - profiling

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

test_ci_push:
  stage: profiling
  allow_failure: false
  script:
    - git remote set-url upstream https://${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN}@github.com/CubicrootXYZ/lightweight-monitoring.git
    - git fetch upstream
    - git checkout upstream/main
    - git merge origin/master --allow-unrelated-histories
    - git push HEAD:upstream/main
    - git checkout origin/master
    - git merge upstream/main --allow-unrelated-histories
    - git push HEAD:master