default:
  image: docker:latest

stages:
  - github_push
  - build

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

github_sync:
  stage: github_push
  allow_failure: false
  only:
    - master
  script:
    - git remote set-url upstream https://${GITHUB_USERNAME}:${GITHUB_ACCESS_TOKEN}@github.com/CubicrootXYZ/lightweight-monitoring.git
    - git fetch upstream
    - git checkout upstream/main
    - git merge origin/master --allow-unrelated-histories
    - git push upstream HEAD:main

build_image:
  stage: build
  allow_failure: false
  script:
    - docker build -t cubicrootxyz/lightweight-monitoring .
    - docker login -u="${DOCKERHUB_USERNAME}" -p="${DOCKERHUB_PASSWORD}"
    - docker push cubicrootxyz/lightweight-monitoring
